name: Twilio Functions - DEVELOP
on:
  push:
    branches:
      - dev
    paths:
      - 'Functions/**/*'
      - '.github/workflows/*_function_deploy.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Flex-DEVenv
    steps:
      - name: Preparing Repository
        uses: actions/checkout@v4
      - name: Installing NodeJS and NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Functions/package-lock.json
      - name: Installing Packages 
        working-directory: Functions
        run: npm install twilio-cli -g;twilio plugins:install @twilio-labs/plugin-serverless;npm install
      - name: Deploying Functions
        working-directory: Functions
        env:
          TWILIO_ACCOUNT_SID: ${{secrets.ACCOUNT_SID}} 
          TWILIO_API_KEY: ${{secrets.TWILIO_API_KEY}}
          TWILIO_API_SECRET: ${{secrets.TWILIO_API_SECRET}}
        run: twilio serverless:deploy --environment=dev --force -n bmg-elexial-cc-stack --override-existing-project

  
       