name: Twilio Functions - DEVELOP
on:
  pull_request:
    branches:
      - staging
    types: [closed] 
jobs:
  precheck:
    if: github.event.pull_request.merged == true
    outputs:
      run_job: ${{ steps.checkfiles.outputs.run_job }}
    runs-on: ubuntu-latest
    environment: Flex-DEVenv
    steps:
      - name: Preparing Repository
        uses: actions/checkout@v4
      - name: Checking for Changes in Functions
        id: checkfiles
        run: |
          echo "::set-output name=run_job::$(curl -s  -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files | jq -r '.[]  .filename' | cut -d "/" -f 1,2 | jq -R -s -c 'split("\n")[:-1]' | jq '. | contains (["Functions/"])')"
      - run: |
          echo ${{steps.checkfiles.outputs.run_job}}
  build:
    needs: precheck
    if: needs.precheck.outputs.run_job == 'true' 
    runs-on: ubuntu-latest
    environment: Flex-DEVenv
    steps:
      - name: Preparing Repository
        uses: actions/checkout@v4
      - name: Installing NodeJS and NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Installing Packages 
        working-directory: Functions
        run: npm install twilio-cli -g;twilio plugins:install @twilio-labs/plugin-serverless;npm install
      - name: Deploying Functions
        working-directory: Functions
        env:
          TWILIO_ACCOUNT_SID: ${{secrets.ACCOUNT_SID}} 
          TWILIO_API_KEY: ${{secrets.TWILIO_API_KEY}}
          TWILIO_API_SECRET: ${{secrets.TWILIO_API_SECRET}}
          HUBSPOT_TOKEN: ${{secrets.HUBSPOT_TOKEN}}
          INBOUND_SMS_STUDIO_FLOW: ${{secrets.INBOUND_SMS_STUDIO_FLOW}}
          TASK_ROUTER_WORKSPACE_SID: ${{secrets.TASK_ROUTER_WORKSPACE_SID}}
          TASK_ROUTER_WORKFLOW_SID: ${{secrets.TASK_ROUTER_WORKFLOW_SID}}
          TASK_ROUTER_QUEUE_SID: ${{secrets.TASK_ROUTER_QUEUE_SID}}
          TWILIO_PHONE_NUMBER: ${{secrets.TWILIO_PHONE_NUMBER}}
          TWILIO_WA_PHONE_NUMBER: ${{secrets.TWILIO_WA_PHONE_NUMBER}}
        run: twilio serverless:deploy --environment=dev --force -n bmg-elexial-cc-stack --override-existing-project --env .env.example

  
       